config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
  }

  devise_scope :user do
    unauthenticated do
      root to: 'users/sessions#new', as: 'unauthenticated_user_root'
    end

    authenticated do
      root to: "projects#index", as: 'authenticated_user_root'

      resources :project_statuses
      resources :comments
      resources :user_projects
      resources :projects
      resources :users
    end
  end
end

app/controllers/project_statuses_controller.rb
class ProjectStatusesController < ApplicationController
  before_action :set_project_status, only: %i[ show edit update destroy ]

  # GET /project_statuses or /project_statuses.json
  def index
    @project_statuses = ProjectStatus.all
  end

  # GET /project_statuses/1 or /project_statuses/1.json
  def show
  end

  # GET /project_statuses/new
  def new
    @project_status = ProjectStatus.new
  end

  # GET /project_statuses/1/edit
  def edit
  end

  # POST /project_statuses or /project_statuses.json
  def create
    @project_status = ProjectStatus.new(project_status_params)

    respond_to do |format|
      if @project_status.save
        format.html { redirect_to @project_status, notice: "Project status was successfully created." }
        format.json { render :show, status: :created, location: @project_status }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /project_statuses/1 or /project_statuses/1.json
  def update
    respond_to do |format|
      if @project_status.update(project_status_params)
        format.html { redirect_to @project_status, notice: "Project status was successfully updated." }
        format.json { render :show, status: :ok, location: @project_status }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /project_statuses/1 or /project_statuses/1.json
  def destroy
    @project_status.destroy!

    respond_to do |format|
      format.html { redirect_to project_statuses_path, status: :see_other, notice: "Project status was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project_status
      @project_status = ProjectStatus.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_status_params
      params.require(:project_status).permit(:status, :user_id, :project_id)
    end
end

app/helpers/project_statuses_helper.rb
module ProjectStatusesHelper
end

app/views/project_statuses/_form.html.erb
<%= form_with(model: project_status) do |form| %>
  <% if project_status.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project_status.errors.count, "error") %> prohibited this project_status from being saved:</h2>

      <ul>
        <% project_status.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.number_field :status %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :project_id, style: "display: block" %>
    <%= form.text_field :project_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/project_statuses/_project_status.html.erb
<div id="<%= dom_id project_status %>">
  <p>
    <strong>Status:</strong>
    <%= project_status.status %>
  </p>

  <p>
    <strong>User:</strong>
    <%= project_status.user_id %>
  </p>

  <p>
    <strong>Project:</strong>
    <%= project_status.project_id %>
  </p>

</div>

app/views/project_statuses/edit.html.erb
<h1>Editing project status</h1>

<%= render "form", project_status: @project_status %>

<br>

<div>
  <%= link_to "Show this project status", @project_status %> |
  <%= link_to "Back to project statuses", project_statuses_path %>
</div>

app/views/project_statuses/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Project statuses</h1>

<div id="project_statuses">
  <% @project_statuses.each do |project_status| %>
    <%= render project_status %>
    <p>
      <%= link_to "Show this project status", project_status %>
    </p>
  <% end %>
</div>

<%= link_to "New project status", new_project_status_path %>

app/views/project_statuses/new.html.erb
<h1>New project status</h1>

<%= render "form", project_status: @project_status %>

<br>

<div>
  <%= link_to "Back to project statuses", project_statuses_path %>
</div>

app/views/project_statuses/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @project_status %>

<div>
  <%= link_to "Edit this project status", edit_project_status_path(@project_status) %> |
  <%= link_to "Back to project statuses", project_statuses_path %>

  <%= button_to "Destroy this project status", @project_status, method: :delete %>
</div>