config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
  }

  devise_scope :user do
    unauthenticated do
      root to: 'users/sessions#new', as: 'unauthenticated_user_root'
    end

    authenticated do
      root to: "projects#index", as: 'authenticated_user_root'

      resources :project_statuses
      resources :comments
      resources :user_projects
      resources :projects
      resources :users
    end
  end
end

app/views/shared/_comment.html.erb
<p class="flex justify-between py-1 px-2 my-2 border-solid border-2 border-grey-200 rounded-md">
<span><span class="font-bold"><%= comment.user.full_name %>:</span> <%= comment[:description] %></span>
<span class="min-w-fit ml-3"><%= comment[:created_at] %></span>
</p>

app/views/shared/_nav.html.erb
<nav class="flex flex-row justify-between p-8 border-solid border-b-2 border-sky-500">
  <%= link_to "Homey", authenticated_user_root_path, class: "font-bold underline" %>
  <% if user_signed_in? %>
    <%= button_to "Sign out", destroy_user_session_path, method: :delete  %>
  <% end %>
</nav>

app/views/shared/_project_status.html.erb
<p class="flex justify-between text-gray-500 py-1 px-2 my-2">
Project status update by <%= project_status.user.full_name %>: <%= project_status[:status] %>
<span class="min-w-fit"><%= project_status[:created_at] %></span>
</p>